{{- if and .Values.agent.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tote.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tote.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end }}
