{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tote.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tote.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "tote.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
{{- end }}
