{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tote.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tote.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "tote.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
